FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
        openjdk-21-jdk \
        maven \
        git \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
